import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { logger } from '../utils/logger.js';

function formatDate(iso) {
  if (!iso || iso === 'unknown') return 'Unknown';
  return iso.slice(0, 10);
}

function jobEntry(job) {
  const score = job.score !== null ? `${job.score}/10` : 'unscored';
  const heading = `## ${job.score !== null ? `Score ${score} — ` : ''}${job.title} @ ${job.company}`;
  const tags = job.tags.length ? job.tags.map(t => `\`${t}\``).join(', ') : '_none_';
  const tailoredLine = job.tailoredPath
    ? `\n- **Tailored resume**: [\`${job.tailoredPath}\`](${job.tailoredPath})`
    : '';
  const reasonLine = job.scoreReason ? `\n- **Why matched**: ${job.scoreReason}` : '';
  const excerpt = job.description ? `\n> **Excerpt**: ${job.description.slice(0, 200).replace(/\n/g, ' ')}…` : '';

  return `${heading}

- **Location**: ${job.location || 'Not specified'}
- **Source**: ${job.source.charAt(0).toUpperCase() + job.source.slice(1)} — [View Job](${job.url})
- **Posted**: ${formatDate(job.postedAt)}
- **Tags**: ${tags}${reasonLine}${tailoredLine}
${excerpt}`;
}

export function writeReport(jobs, stats, config) {
  const date = new Date().toISOString().slice(0, 10);
  const outDir = config.output.directory;

  mkdirSync(join(outDir), { recursive: true });
  mkdirSync(join(outDir, 'resumes'), { recursive: true });

  const sourcesUsed = [...new Set(jobs.map(j => j.source))]
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join(', ') || 'none';

  const header = `# Job Search Results — ${date}

**Profile**: ${config.profile.seniorityLevel.charAt(0).toUpperCase() + config.profile.seniorityLevel.slice(1)}-level Frontend Developer (${config.profile.targetRoles.slice(0, 3).join(', ')})
**Sources**: ${sourcesUsed}
**Total fetched**: ${stats.totalFetched} | **After pre-filter**: ${stats.afterPrefilter} | **Shown**: ${jobs.length}

---
`;

  const body = jobs.length
    ? jobs.map(jobEntry).join('\n\n---\n\n')
    : '_No jobs matched your criteria. Try adjusting config.json (loosen skills, locations, or seniority)._';

  const footer = `\n\n---\n_Generated by job-search-cli on ${date}. Job data via Remotive, The Muse, and Greenhouse public APIs. [Remotive attribution required by their API terms.](https://remotive.com)_\n`;

  const content = header + body + footer;
  const filePath = join(outDir, `jobs-${date}.md`);

  writeFileSync(filePath, content, 'utf8');
  logger.info(`[reporter] Report written: ${filePath}`);

  return filePath;
}
